In [ ]:
#mahesh.s 
#20202aie0005
#ai branch(mtech) presidency
#professor- Dr smitha rao

#import libaries
import numpy as np 
import pandas as pd 
import os
import json

from sklearn.model_selection import train_test_split

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer


from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix


In [ ]:
#read the csv
df= pd.read_csv(r"/content/cleaned_tweets.csv")


In [ ]:
df.head()

message  label
0                 real good moment missssssssss much    0.0
1               reading manga http plurk com p mzp1e    0.0
2  comeagainjen http twitpic com y2lx http www yo...    0.0
3  lapcat need send em accountant tomorrow oddly ...    0.0
4                add myspace myspace com lookthunder    0.0

In [ ]:
#methord 1

#import variable X
import json
with open("/content/X.txt", "r") as fp:
  X = json.load(fp)



In [ ]:
#methord 2
c = df['message'].astype('str').values

In [ ]:
#spliting the dataset
x_train, x_test, y_train, y_test = train_test_split(X, df.label, test_size=0.2, random_state = 42)

In [ ]:
#unknown data
qtest = ['depressed','happy','i am sad','i am happy','i am sleepy','tears of joy','i am depressed','happy tears']

In [ ]:
1# naive_bayes model
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer

nb = Pipeline([('vect', CountVectorizer()),
               ('tfidf', TfidfTransformer()),
               ('clf', MultinomialNB()),
              ])
nb.fit(x_train, y_train)

Pipeline(memory=None,
         steps=[('vect',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('tfidf',
                 TfidfTransformer(norm='l2', smooth_idf=True,
                                  sublinear_tf=False, use_idf=True)),
                ('clf',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [ ]:
1# naive_bayes model prediction
y_pred = nb.predict(x_test)

print('accuracy %s' % accuracy_score(y_pred, y_test))
print(" "*30)
print('roc_auc_score %s' % roc_auc_score(y_pred, y_test))
print(" "*30)
print('confusion_matrix ')
print(confusion_matrix(y_pred, y_test))
print(" "*30)

print(classification_report(y_test, y_pred, digits=5))

accuracy 0.9143272023233301
                              
roc_auc_score 0.9456418155223616
                              
confusion_matrix 
[[1584  174]
 [   3  305]]
                              
              precision    recall  f1-score   support

         0.0    0.90102   0.99811   0.94709      1587
         1.0    0.99026   0.63674   0.77510       479

    accuracy                        0.91433      2066
   macro avg    0.94564   0.81743   0.86109      2066
weighted avg    0.92171   0.91433   0.90721      2066



In [ ]:
1#naive_bayes model unknown text prediction
print(qtest)
nb.predict(qtest)

['depressed', 'happy', 'i am sad', 'i am happy', 'i am sleepy', 'tears of joy', 'i am depressed', 'happy tears']


array([1., 0., 1., 0., 0., 1., 1., 0.])

In [ ]:
2#logistic regression model
from sklearn.linear_model import LogisticRegression

logreg = Pipeline([('vect', CountVectorizer()),
                ('tfidf', TfidfTransformer()),
                ('clf', LogisticRegression(n_jobs=1, C=1e5)),
               ])
logreg.fit(x_train, y_train)


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


Pipeline(memory=None,
         steps=[('vect',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('tfidf',
                 TfidfTransformer(norm='l2', smooth_idf=True,
                                  sublinear_tf=False, use_idf=True)),
                ('clf',
                 LogisticRegression(C=100000.0, class_weight=None, dual=False,
                                    fit_intercept=True, intercept_scaling=

In [ ]:
2##logistic regression model prediction
y_pred = logreg.predict(x_test)

print('accuracy %s' % accuracy_score(y_pred, y_test))
print(" "*30)
print('roc_auc_score %s' % roc_auc_score(y_pred, y_test))
print(" "*30)
print('confusion_matrix ')
print(confusion_matrix(y_pred, y_test))
print(" "*30)

print(classification_report(y_test, y_pred, digits=5))

accuracy 0.968054211035818
                              
roc_auc_score 0.9470683761654383
                              
confusion_matrix 
[[1539   18]
 [  48  461]]
                              
              precision    recall  f1-score   support

         0.0    0.98844   0.96975   0.97901      1587
         1.0    0.90570   0.96242   0.93320       479

    accuracy                        0.96805      2066
   macro avg    0.94707   0.96609   0.95610      2066
weighted avg    0.96926   0.96805   0.96839      2066



In [ ]:
2#logistic regression model unknown prediction
print(qtest)
logreg.predict(qtest)

['depressed', 'happy', 'i am sad', 'i am happy', 'i am sleepy', 'tears of joy', 'i am depressed', 'happy tears']


array([1., 0., 1., 0., 1., 1., 1., 0.])

In [ ]:
3# KNeighborsClassifier model
from sklearn.neighbors import KNeighborsClassifier

knc = Pipeline([('vect', CountVectorizer()),
                ('tfidf', TfidfTransformer()),
                ('clf',  KNeighborsClassifier(3))
                ])

knc.fit(x_train, y_train)


Pipeline(memory=None,
         steps=[('vect',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('tfidf',
                 TfidfTransformer(norm='l2', smooth_idf=True,
                                  sublinear_tf=False, use_idf=True)),
                ('clf',
                 KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                      metric='minkowski', metric_params=None,
     

In [ ]:
3#KNeighborsClassifier model prediction
y_pred = knc.predict(x_test)

print('accuracy %s' % accuracy_score(y_pred, y_test))
print(" "*30)
print('roc_auc_score %s' % roc_auc_score(y_pred, y_test))
print(" "*30)
print('confusion_matrix ')
print(confusion_matrix(y_pred, y_test))
print(" "*30)

print(classification_report(y_test, y_pred, digits=5))

accuracy 0.2894482090997096
                              
roc_auc_score 0.6187469459729333
                              
confusion_matrix 
[[ 120    1]
 [1467  478]]
                              
              precision    recall  f1-score   support

         0.0    0.99174   0.07561   0.14052      1587
         1.0    0.24576   0.99791   0.39439       479

    accuracy                        0.28945      2066
   macro avg    0.61875   0.53676   0.26745      2066
weighted avg    0.81878   0.28945   0.19938      2066



In [ ]:
3#KNeighborsClassifier unknown prediction
print(qtest)
knc.predict(qtest)

['depressed', 'happy', 'i am sad', 'i am happy', 'i am sleepy', 'tears of joy', 'i am depressed', 'happy tears']


array([1., 0., 1., 0., 0., 1., 1., 1.])

In [ ]:
4# LogisticRegressionCV model
from sklearn.linear_model import LogisticRegressionCV


regcv = Pipeline([('vect', CountVectorizer()),
                ('tfidf', TfidfTransformer()),
                ('clf', LogisticRegressionCV()),
               ])
regcv.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


Pipeline(memory=None,
         steps=[('vect',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=Non...
                 TfidfTransformer(norm='l2', smooth_idf=True,
                                  sublinear_tf=False, use_idf=True)),
                ('clf',
                 LogisticRegressionCV(Cs=10, class_weight=None, cv=None,
                                      dual=False, fit_intercept=True,
                                     

In [ ]:
4#LogisticRegressionCV  model prediction
y_pred = regcv.predict(x_test)

print('accuracy %s' % accuracy_score(y_pred, y_test))
print(" "*30)
print('roc_auc_score %s' % roc_auc_score(y_pred, y_test))
print(" "*30)
print('confusion_matrix ')
print(confusion_matrix(y_pred, y_test))
print(" "*30)

print(classification_report(y_test, y_pred, digits=5))

accuracy 0.9888673765730881
                              
roc_auc_score 0.9905188327881594
                              
confusion_matrix 
[[1584   20]
 [   3  459]]
                              
              precision    recall  f1-score   support

         0.0    0.98753   0.99811   0.99279      1587
         1.0    0.99351   0.95825   0.97556       479

    accuracy                        0.98887      2066
   macro avg    0.99052   0.97818   0.98418      2066
weighted avg    0.98892   0.98887   0.98880      2066



In [ ]:
4#LogisticRegressionCV model unknown prediction
print(qtest)
regcv.predict(qtest)

['depressed', 'happy', 'i am sad', 'i am happy', 'i am sleepy', 'tears of joy', 'i am depressed', 'happy tears']


array([1., 0., 0., 0., 0., 0., 1., 0.])

In [ ]:
5# other random models testing

from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis


rand = Pipeline([('vect', CountVectorizer()),
                ('tfidf', TfidfTransformer()),
                ('clf', RandomForestClassifier()),
               ])
rand.fit(x_train, y_train)

Pipeline(memory=None,
         steps=[('vect',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=Non...
                 RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                        class_weight=None, criterion='gini',
                                        max_depth=None, max_features='auto',
                                        max_leaf_nodes=None, max_samples=None,
                                

In [ ]:
5#random model prediction
y_pred = rand.predict(x_test)

print('accuracy %s' % accuracy_score(y_pred, y_test))
print(" "*30)
print('roc_auc_score %s' % roc_auc_score(y_pred, y_test))
print(" "*30)
print('confusion_matrix ')
print(confusion_matrix(y_pred, y_test))
print(" "*30)

print(classification_report(y_test, y_pred, digits=5))

accuracy 0.9607938044530494
                              
roc_auc_score 0.9332454092288291
                              
confusion_matrix 
[[1522   16]
 [  65  463]]
                              
              precision    recall  f1-score   support

         0.0    0.98960   0.95904   0.97408      1587
         1.0    0.87689   0.96660   0.91956       479

    accuracy                        0.96079      2066
   macro avg    0.93325   0.96282   0.94682      2066
weighted avg    0.96347   0.96079   0.96144      2066



In [ ]:
5#random unknown prediction
print(qtest)
rand.predict(qtest)

['depressed', 'happy', 'i am sad', 'i am happy', 'i am sleepy', 'tears of joy', 'i am depressed', 'happy tears']


array([1., 0., 1., 0., 1., 1., 1., 0.])

In [ ]:
# naive_bayes model =nb
#logistic regression model =logreg
#KNeighborsClassifier model model = knc
#LogisticRegressionCV model = regcv
#random = rand
models=[nb,logreg,knc,regcv,rand]


input_tweets = [str(x) for x in input("Enter tweet (if multiple tweets sep=','): ").split(","and'.',-1)]

print("the tweet is : ", input_tweets) 
print("*"*50) 
print(" 0 is not depressed and 1 is depressed : ")
print("*"*50)  


# prediction
print(input_tweets,"naive_bayes model")
print(nb.predict(input_tweets))
print("="*20) 

print(input_tweets,"logistic regression model")
print(logreg.predict(input_tweets))
print("="*20) 

print(input_tweets,"KNeighborsClassifier model")
print(knc.predict(input_tweets))
print("="*20) 

print(input_tweets,"LogisticRegressionCV model")
print(regcv.predict(input_tweets))
print("="*20) 

print(input_tweets,"random model")
print(rand.predict(input_tweets))
print("*"*50) 

#real sucide notes to test:

#I am going to die in office…Please leave immediately if you have a weak stomach or mind since I don’t want to cause physical or mental distress.
#Things just seemed to go too wrong too many times.
#I am haunted by the vivid memories of killings and corpses and anger and pain of starving or wounded children, of trigger-happy madmen, often police, of killer executioners
#I myself and my wife – in order to escape the disgrace of deposition or capitulation – choose death
#I don't want to hurt you or anybody so please forget about me. Just try. Find yourself a better friend
#When all usefulness is over, when one is assured of an unavoidable and imminent death, it is the simplest of human rights to choose a quick and easy death in place of a slow and horrible one
#Death is before me today As a man longs to see his houseWhen he has spent years in captivity

Enter tweet (if multiple tweets sep=','): jnjjkn
the tweet is :  ['jnjjkn']
**************************************************
 0 is not depressed and 1 is depressed : 
**************************************************
['jnjjkn'] naive_bayes model
[0.]
['jnjjkn'] logistic regression model
[1.]
['jnjjkn'] KNeighborsClassifier model
[1.]
['jnjjkn'] LogisticRegressionCV model
[0.]
['jnjjkn'] random model
[1.]
**************************************************


In [ ]:
import joblib

joblib.dump(logreg,'model.pkl')

['model.pkl']

In [ ]:
pipe = joblib.load('/content/model.pkl')
pipe.predict(qtest)

array([1., 0., 1., 0., 1., 1., 1., 0.])

#conclusion
i choose logistic regression as my best model as it is generalized well and its roc_auc_score is 0.94